unique_ids:
  assets:
    standard-page.html: BFUE7N6I6QB6LHGZQKAAMCKCLNX4MNE2
    theme.css: ANNGDKMPWDGHMM3NZ3YPQ6JOSGEKAOP7
  forms:
    Form1: ZHOXB5MIZZE25PJ3HKYWH75XU5O3QIMF
  modules: {}
  scripts: {}
  server_modules: {}
